dependencies:

  - name: kube-state-metrics
    version: 0.14.*
    repository: "file://../kube-state-metrics"
    condition: kubeStateMetrics.enabled

  - name: prometheus-node-exporter
    version: 1.3.*
    repository: "file://../prometheus-node-exporter"
    condition: nodeExporter.enabled

  - name: grafana
    version: 2.3.*
    repository: "file://../grafana"
    condition: grafana.enabled
